# Generated by Django 4.1 on 2022-09-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_igallery_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='subject',
            new_name='ssubject',
        ),
    ]
