# Generated by Django 4.1 on 2022-09-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_subject_slider_ssubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncity', models.CharField(max_length=30)),
                ('cpic', models.ImageField(upload_to='static/city/')),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ncategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('cpic', models.ImageField(null=True, upload_to='static/category')),
                ('cdate', models.DateField()),
            ],
        ),
    ]
