# Generated by Django 4.1 on 2022-09-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_mynews_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynews',
            name='ncategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.ncategory'),
        ),
        migrations.AddField(
            model_name='mynews',
            name='ncity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.city'),
        ),
    ]
