# Generated by Django 4.1 on 2022-09-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_mynews_ncategory_mynews_ncity'),
    ]

    operations = [
        migrations.CreateModel(
            name='topheadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=500)),
            ],
        ),
    ]
